package steam.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import steam.domain.CDKey;
import steam.domain.CDKeyExample;

@Repository
public interface CDKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdkey
     *
     * @mbggenerated
     */
    int countByExample(CDKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdkey
     *
     * @mbggenerated
     */
    int deleteByExample(CDKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdkey
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cdkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdkey
     *
     * @mbggenerated
     */
    int insert(CDKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdkey
     *
     * @mbggenerated
     */
    int insertSelective(CDKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdkey
     *
     * @mbggenerated
     */
    List<CDKey> selectByExample(CDKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdkey
     *
     * @mbggenerated
     */
    CDKey selectByPrimaryKey(String cdkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdkey
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CDKey record, @Param("example") CDKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdkey
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CDKey record, @Param("example") CDKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdkey
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CDKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdkey
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CDKey record);
}